config/routes.rb
Rails.application.routes.draw do

  scope controller: :index do
    root action: :index
    get :signin, :signup, :forgot
    post 'subscribe/:banner_id' => :subscribe, as: :subscribe
  end

  resources :users, only: :create
  resources :sessions, only: %i(create destroy)
  namespace :auth do
    post :change_password
    get ":provider/callback" => :callback, as: :proviter_callback
    post ":provider/commit/:uid" => :commit, as: :commit
  end
  namespace :profile do
    root action: :show
    put '' => :update
    put :password, :avatar
  end

  get ':kind/new' => 'posts#new', constraints: { kind: /articles|blog_posts/ }, as: :new_post
  resources :posts, only: %i(create edit update destroy), controller: :posts do
    member do
      post :like
      delete 'like' => :dislike
    end
  end
  resources :articles, only: %i(index show) do
    collection { get "tags/:tag", action: :by_tag, as: :tag }
  end

  scope 'blogs', controller: 'blogs' do
    root action: :index, as: 'blogs'
    scope ':blog_id', as: 'blog' do
      post 'follow' => :follow
      delete 'follow' => :unfollow
      root 'blog_posts#index', as: ''
      resources :blog_posts, only: %i(index show), path: :posts, as: :posts
    end
  end

  # resources :blogs, only: :index do
  #   member do
  #     post 'follow'
  #     delete 'follow' => :unfollow
  #   end
  #   resources :blog_posts, only: %i(index show new create edit update destroy), path: :posts, as: :posts
  # end

  namespace :admin do
    root 'dashboard#index'
    resources :banners, only: %i(index new create edit update)
  end

end

app/models/article.rb
class Article < Post
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  load_and_authorize_resource find_by: :slug


  def index
    @articles = Article.most_recent.includes(:user).page(params[:page])
    render(partial: 'previews', locals: { posts: @articles }) if request.xhr?
  end

  def by_tag
    @articles = Article.by_tag(params[:tag]).most_recent.includes(:user).page(params[:page])
    if request.xhr?
      render partial: 'previews', locals: { posts: @articles }
    else
      @total_count = Article.by_tag(params[:tag]).count
    end
    render :index
  end

end

app/views/articles/_previews.html.slim
- posts.each do |post|
  li.post-preview.panel
    .panel-body
      .header
        .pull-right
          ul.list-inline.controls
            - if can? :edit, post
              li
                = link_to edit_post_path(post)
                  = fa_icon :edit
            - if can? :destroy, post
              li
                = link_to post_path(post), method: :delete, data: { confirm: 'Are you sure?' }
                  = fa_icon :trash

        h3.title = link_to post.title, article_path(post)
        ul.list-inline.details.info
          li
            => fa_icon 'clock-o'
            | #{ time_ago_in_words post.created_at } назад
          li = react_component 'Like', liked: post.liked_by?(current_user), likesCount: post.likes.count, url: like_post_path(post), isLoggedIn: logged_in?
          li
            ul.list-inline
              - post.tags.each do |tag|
                li = link_to "##{tag}", tag_articles_path(tag: tag), class: "label label-primary"

      = sanitize truncate(post.text, 500)

app/views/articles/index.html.slim
.row
  .col-md-12
    h2.page-title = fa_icon :briefcase, text: 'Кейсы'

    ul.list-unstyled role="preview-list"
      = render partial: 'previews', locals: { posts: @articles }
    .text-center = link_to 'Загрузить еще', 'javascript:;', class: 'btn btn-primary', role: 'load-more', data: { url: articles_path }

app/views/articles/index_by_tag.html.slim
.row
  .col-md-12
    h2
      b> = "##{ params[:tag] }"
      small = "(всего #{ @total_count })"
    br

.row
  .col-md-12
    ul.list-unstyled role="preview-list"
      = render partial: 'previews', locals: { posts: @articles }
    .text-center = link_to 'Загрузить еще', 'javascript:;', class: 'btn btn-primary', role: 'load-more', data: { url: tag_articles_path(tag: params[:tag]) }

app/views/articles/show.html.slim
.row
  .col-md-12.post-details.panel
    .panel-body
      h1.title = @article.title

      .content = sanitize @article.text

      hr
      ul.list-inline.controls
        - if can? :edit, @article
          li = link_to edit_post_path(@article)
            = fa_icon :edit
        - if can? :destroy, @article
          li = link_to post_path(@article), method: :delete, data: { confirm: 'Are you sure?' }
            = fa_icon :trash