config/routes.rb
Rails.application.routes.draw do

  scope controller: :index do
    root action: :index
    get :signin, :signup, :forgot
    post 'subscribe/:banner_id' => :subscribe, as: :subscribe
  end

  resources :users, only: :create
  resources :sessions, only: %i(create destroy)
  namespace :auth do
    post :change_password
    get ":provider/callback" => :callback, as: :proviter_callback
    post ":provider/commit/:uid" => :commit, as: :commit
  end
  namespace :profile do
    root action: :show
    put '' => :update
    put :password, :avatar
  end

  get ':kind/new' => 'posts#new', constraints: { kind: /articles|blog_posts/ }, as: :new_post
  resources :posts, only: %i(create edit update destroy), controller: :posts do
    member do
      post :like
      delete 'like' => :dislike
    end
  end
  resources :articles, only: %i(index show) do
    collection { get "tags/:tag", action: :by_tag, as: :tag }
  end

  scope 'blogs', controller: 'blogs' do
    root action: :index, as: 'blogs'
    scope ':blog_id', as: 'blog' do
      post 'follow' => :follow
      delete 'follow' => :unfollow
      root 'blog_posts#index', as: ''
      resources :blog_posts, only: %i(index show), path: :posts, as: :posts
    end
  end

  # resources :blogs, only: :index do
  #   member do
  #     post 'follow'
  #     delete 'follow' => :unfollow
  #   end
  #   resources :blog_posts, only: %i(index show new create edit update destroy), path: :posts, as: :posts
  # end

  namespace :admin do
    root 'dashboard#index'
    resources :banners, only: %i(index new create edit update)
  end

end

app/models/blog_post.rb
class BlogPost < Post

  def blog
    Blog.find(post.user.slug)
  end

end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController

  before_action :check_authentication, only: :new
  before_action :load_blog
  load_and_authorize_resource find_by: :slug, except: :create


  def index
    @blog_posts = @blog.posts.most_recent.page(params[:page])
    render(partial: 'previews', locals: { posts: @blog_posts }) if request.xhr?
  end


  private

  def load_blog
    @blog = Blog.find(params[:blog_id])
  end

end

app/views/blog_posts/_header.html.slim
.blog-header
  .gradient
  .info
    .userpic style="background-image: url(#{ @blog.user.avatar.thumb('200x200').url })"
  .details
    h1 = link_to @blog.user.name, blog_path(@blog)
    p.hidden-xs = @blog.user.profile['bio']
    - if can? :follow, @blog.user
      - if @blog.is_followed_by?(current_user)
        = link_to 'Отменить подписку', blog_follow_path(@blog), method: :delete, class: 'btn btn-primary follow-link'
      - else
        = link_to 'Подписаться', blog_follow_path(@blog), method: :post, class: 'btn btn-primary follow-link'

app/views/blog_posts/_previews.html.slim
- posts.each do |post|
  li.post-preview.panel
    .panel-body
      .header
        .pull-right
          ul.list-inline.controls
            - if can? :edit, post
              li
                = link_to edit_post_path(post)
                  = fa_icon :edit
            - if can? :destroy, post
              li
                = link_to post_path(post), method: :delete, data: { confirm: 'Are you sure?' }
                  = fa_icon :trash

        h3.title = link_to post.title, blog_post_path(@blog, post)
        ul.list-inline.details.info
          li
            => fa_icon 'clock-o'
            | #{ time_ago_in_words post.created_at } назад
          li = react_component 'Like', liked: post.liked_by?(current_user), likesCount: post.likes.count, url: like_post_path(post), isLoggedIn: logged_in?
          li
            ul.list-inline
              - post.tags.each do |tag|
                li = link_to "##{tag}", tag_articles_path(tag: tag), class: "label label-primary"

      = sanitize truncate(post.text, 500)

app/views/blog_posts/index.html.slim
= render partial: 'header'

- if @blog.followers.any?
  .row.followers
    .col-md-12
      - @blog.followers.each do |user|
        = avatar user, :tiny, class: 'userpic'
  hr

.row
  .col-md-12
    ul.list-unstyled role="preview-list"
      li = render partial: 'blog_posts/previews', locals: { posts: @blog.posts }
    .text-center = link_to 'Загрузить еще', 'javascript:;', class: 'btn btn-primary', role: 'load-more', data: { url: blog_posts_path(@blog) }

app/views/blog_posts/show.html.slim
= render partial: 'header'
br

.post-details.panel
  .panel-body
    h1.title = @blog_post.title

    .content = sanitize @blog_post.text

    hr
    ul.list-inline.controls
      - if can? :edit, @blog_post
        li = link_to edit_post_path(@blog_post)
          = fa_icon :edit
      - if can? :destroy, @blog_post
        li = link_to post_path(@blog_post), method: :delete, data: { confirm: 'Are you sure?' }
          = fa_icon :trash