config/routes.rb
Rails.application.routes.draw do

  scope controller: :index do
    root action: :index
    get :signin, :signup, :forgot
    post 'subscribe/:banner_id' => :subscribe, as: :subscribe
  end

  resources :users, only: :create
  resources :sessions, only: %i(create destroy)
  namespace :auth do
    post :change_password
    get ":provider/callback" => :callback, as: :proviter_callback
    post ":provider/commit/:uid" => :commit, as: :commit
  end
  namespace :profile do
    root action: :show
    put '' => :update
    put :password, :avatar
  end

  get ':kind/new' => 'posts#new', constraints: { kind: /articles|blog_posts/ }, as: :new_post
  resources :posts, only: %i(create edit update destroy), controller: :posts do
    member do
      post :like
      delete 'like' => :dislike
    end
  end
  resources :articles, only: %i(index show) do
    collection { get "tags/:tag", action: :by_tag, as: :tag }
  end

  scope 'blogs', controller: 'blogs' do
    root action: :index, as: 'blogs'
    scope ':blog_id', as: 'blog' do
      post 'follow' => :follow
      delete 'follow' => :unfollow
      root 'blog_posts#index', as: ''
      resources :blog_posts, only: %i(index show), path: :posts, as: :posts
    end
  end

  # resources :blogs, only: :index do
  #   member do
  #     post 'follow'
  #     delete 'follow' => :unfollow
  #   end
  #   resources :blog_posts, only: %i(index show new create edit update destroy), path: :posts, as: :posts
  # end

  namespace :admin do
    root 'dashboard#index'
    resources :banners, only: %i(index new create edit update)
  end

end

app/views/index/_banners.html.slim
- if @banners.any?

  #banners.carousel.slide.panel
    .carousel-inner role="listbox"
      - @banners.each_with_index do |banner, index|
        .item class="#{ 'active' if index.zero? }"
          .banner style="background-color: ##{ banner.color.presence }"
            .image style="background-image: url(#{ ImageManager.fetch(banner.image)})"
            .container
              .content
                h1.title = banner.title

                .text = banner.text

                - if banner.settings['form']
                  .row
                    .col-md-8.col-md-offset-2
                      = form_tag subscribe_path(banner)
                        .input-group
                          = text_field_tag :email, nil, class: 'form-control form-control-sm', placeholder: 'Оставьте свой e-mail'
                          span.input-group-btn = submit_tag 'Подписаться', class: 'btn btn-primary'


    a.left.carousel-control href="#banners" role="button" data-slide="prev"
      span.glyphicon.glyphicon-chevron-left aria-hidden="true"
    a.right.carousel-control href="#banners" role="button" data-slide="next"
      span.glyphicon.glyphicon-chevron-right aria-hidden="true"
    a.close href="javascript:;" role="close-carousel" = fa_icon :times
  hr

app/views/index/_preview_article.html.slim
.post-index.post-preview.panel
  .panel-body
    h3.title = link_to post.title, polymorphic_post_path(post), class: 'title'
    ul.list-inline.details
      li: small = react_component 'Like', liked: post.liked_by?(current_user), likesCount: post.likes.count, url: like_post_path(post), isLoggedIn: logged_in?
      li: small
        = link_to '#'
          => fa_icon 'comments'
          = post.comments.count
      li: small
        => fa_icon 'clock-o'
        | #{ time_ago_in_words post.created_at } назад
    = sanitize truncate(post.text, 300)
    ul.list-inline
      - post.tags.each do |tag|
        li = link_to "##{tag}", tag_articles_path(tag: tag), class: "label label-primary"

app/views/index/_preview_blog_post.html.slim
.post-index.post-preview.panel
  .panel-body
    .info.text-center
      = avatar post.user, :inline
      ul.list-inline
        li = react_component 'Like', liked: post.liked_by?(current_user), likesCount: post.likes.count, url: like_post_path(post), isLoggedIn: logged_in?
        li
          = link_to '#'
            => fa_icon 'comments'
            = post.comments.count

    .main
      h3.title = link_to post.title, polymorphic_post_path(post), class: 'title'
      ul.list-inline.details
        li: small = link_to post.user.name, blog_path(post.user.slug)
        li: small
          => fa_icon 'clock-o'
          | #{ time_ago_in_words post.created_at } назад
      = sanitize truncate(post.text, 300)
      ul.list-inline
        - post.tags.each do |tag|
          li = link_to "##{tag}", tag_articles_path(tag: tag), class: "label label-primary"

app/views/index/forgot.html.slim
hr
.row
  .col-xs-12.col-md-4.col-md-offset-4
    = form_tag auth_change_password_path, novalidate: true
      .form-group
        = email_field_tag :email, nil, placeholder: 'Email', class: 'form-control'
      .form-actions
        button.btn.btn-primary type="submit"
          i.icon-login>
          | Сменить пароль
hr

app/views/index/index.html.slim
= render partial: 'banners'
.row
  .col-md-12
    ul.list-unstyled
      - @posts.each do |post|
        li = render partial: "preview_#{ post.class.name.underscore }", locals: { post: post }

app/views/index/signin.html.slim
.row
  .col-xs-12.col-md-4.col-md-offset-4
    = render partial: '_partials/auth_social'
    hr
    = form_tag sessions_path, role: 'login-form', novalidate: true
      .form-group
        label.control-label for="email" Email
        = email_field_tag :email, params[:email], placeholder: 'Email', class: 'form-control'
      .form-group
        label.control-label for="password" Password
        = password_field_tag :password, nil, placeholder: 'Password', class: 'form-control', autocomplete: 'off'
      .form-actions
        button.btn.btn-primary type="submit"
          i.icon-login>
          = t('auth.signin.submit')
        = link_to t('auth.signin.forgot'), forgot_path, class: ' btn btn-default pull-right'

app/views/index/signup.html.slim
.row
  .col-xs-12.col-md-4.col-md-offset-4
    = render partial: '_partials/auth_social'
    hr
    = form_tag users_path, novalidate: true
      .form-group
        label.control-label Email
        = email_field_tag :'user[email]', params[:email], class: "form-control", autocomplete: 'off'
      .form-group
        label.control-label Password
        = password_field_tag :'user[password]', nil, class: "form-control", autocomplete: 'off'
      .form-group
        label.control-label Password confirmation
        = password_field_tag :'user[password_confirmation]', nil, class: "form-control", autocomplete: 'off'
      .form-actions.text-center
        button.btn.btn-primary type="submit" = t('auth.signup.submit')