config/routes.rb
Rails.application.routes.draw do

  scope controller: :index do
    root action: :index
    get :signin, :signup, :forgot
    post 'subscribe/:banner_id' => :subscribe, as: :subscribe
  end

  resources :users, only: :create
  resources :sessions, only: %i(create destroy)
  namespace :auth do
    post :change_password
    get ":provider/callback" => :callback, as: :proviter_callback
    post ":provider/commit/:uid" => :commit, as: :commit
  end
  namespace :profile do
    root action: :show
    put '' => :update
    put :password, :avatar
  end

  get ':kind/new' => 'posts#new', constraints: { kind: /articles|blog_posts/ }, as: :new_post
  resources :posts, only: %i(create edit update destroy), controller: :posts do
    member do
      post :like
      delete 'like' => :dislike
    end
  end
  resources :articles, only: %i(index show) do
    collection { get "tags/:tag", action: :by_tag, as: :tag }
  end

  scope 'blogs', controller: 'blogs' do
    root action: :index, as: 'blogs'
    scope ':blog_id', as: 'blog' do
      post 'follow' => :follow
      delete 'follow' => :unfollow
      root 'blog_posts#index', as: ''
      resources :blog_posts, only: %i(index show), path: :posts, as: :posts
    end
  end

  # resources :blogs, only: :index do
  #   member do
  #     post 'follow'
  #     delete 'follow' => :unfollow
  #   end
  #   resources :blog_posts, only: %i(index show new create edit update destroy), path: :posts, as: :posts
  # end

  namespace :admin do
    root 'dashboard#index'
    resources :banners, only: %i(index new create edit update)
  end

end

app/views/_partials/_auth_social.html.slim
ul.list-inline.text-center
  li: h1 = link_to icon('facebook-official'), "/auth/facebook"
  li: h1 = link_to icon('vk'), "/auth/vkontakte"

app/views/_partials/_footer.html.slim
hr
| efwoiejo

app/views/_partials/_header.html.slim
nav.navbar-default
  .container-fluid
    / = link_to 'javascript:;', class: 'visible-sm visible-xs'
    /   = fa_icon :bars

    .navbar-text.pull-right
      ul.list-inline
        li
          - if logged_in?
            .dropdown.show
              = link_to 'javascript:;', class: 'dropdown-toggle', id: 'dropdownMenuLink', 'data-toggle'=>"dropdown", 'aria-haspopup'=>"true", 'aria-expanded'=>"false"
                => avatar current_user, :tiny
                span.caret
              ul.dropdown-menu aria-labelledby="dropdownMenuLink"
                li
                  = link_to profile_path
                    = fa_icon :user, text: 'Профиль'
                li.divider
                li
                  = link_to session_path(current_user.id), method: :delete
                    = fa_icon :'sign-out', text: 'Выйти'
          - else
            => link_to 'войти', signin_path
            ' |
            => link_to 'зарегистрироваться', signup_path
        li
          = link_to (logged_in? ? new_post_path(kind: 'blog_posts') : signin_path), class: 'btn btn-primary'
            => fa_icon :plus
            | Новый пост

app/views/_partials/_nav.html.slim
ul.nav
  li
    = active_link_to root_path, active: :exclusive
      = fa_icon :'newspaper-o', text: 'Лента'
  li
    = active_link_to articles_path
      = fa_icon :briefcase, text: 'Кейсы'
  li
    = active_link_to blogs_path
      = fa_icon :'align-left', text: 'Блоги'
  - if can? :enter, :admin
    li
      = active_link_to admin_root_path
        = fa_icon :desktop, text: 'Администрирование'

app/views/_partials/_profile.html.slim
.panel.panel-default.text-center
  .panel-body
    a role="avatar" href="javascript:;"
      = avatar current_user, :profile, class: 'center'
    h4.name = current_user.name
    div
      - current_user.roles.each do |role|
        span.label.label-info => t "user.role.#{role}"

div style="display:none"
  = form_tag profile_avatar_path, method: :put, multipart: true, role: 'avatar-form'
    = file_field_tag :image
    = submit_tag 'Save'